# Generated by Django 5.1.3 on 2024-11-30 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=1000)),
                ('photo', models.URLField()),
                ('type', models.CharField(choices=[('пасив', 'Пасив'), ('актив', 'Актив')], max_length=10)),
                ('alcohol', models.BooleanField(default=False)),
                ('age_restrictions', models.CharField(choices=[('<18', 'Меньше 18'), ('>18', 'Больше 18')], max_length=3)),
                ('gender', models.CharField(choices=[('мужчина', 'Мужчина'), ('женщина', 'Женщина')], max_length=10)),
                ('members', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
