# Generated by Django 5.1.3 on 2024-11-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_new_party_app', '0002_alter_room_members_alter_room_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
